all:
	g++ main.cpp -o banksys front_end.cpp users.cpp login_transaction.cpp logout.cpp create_transaction.cpp deposit_transaction.cpp  paybill_transaction.cpp transaction_file.cpp transfer_transaction.cpp  withdrawal_transaction.cpp enable_transaction.cpp disable_transaction.cpp
banksys : main.cpp
	g++ main.cpp