all: BackEnd.class Transaction.class UserAccounts.class User.class

BackEnd.class: BackEnd.java
	javac BackEnd.java
Transaction.class: Transaction.java
	javac Transaction.java
UserAccounts.class: UserAccounts.java
	javac UserAccounts.java
User.class: User.java
	javac User.java

clean:
	rm *.class